{% set xorg_name = "xcb-proto" %}
{% set xorg_category = "proto" %}
{% set name = "xcb-proto" %}
{% set version = "1.17.0" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://xorg.freedesktop.org/archive/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.gz
  sha256: 392d3c9690f8c8202a68fdb89c16fd55159ab8d65000a6da213f4a1576e97a16
  patches:
    - windows-pythondir.patch  # [win]

build:
  number: 2
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pkg-config
    - m2-autoconf                   # [win]
    - m2-automake{{ am_version }}   # [win]
    - m2-libtool                    # [win]
    - m2-base                         # [win]
    - {{ compiler('c') }}           # [unix]
    - {{ stdlib("c") }}             # [unix]
    - {{ compiler('m2w64_c') }}     # [win]
    - {{ stdlib("m2w64_c") }}       # [win]
    - make                          # [unix]
    - m2-make                       # [win]
    - autoconf                      # [unix]
    - automake                      # [unix]
    - gettext                       # [unix]
    - libtool                       # [unix]
  host:
    - python
    - xorg-util-macros
  run:
    - python

test:
  requires:
    - pkg-config
  imports:
    - xcbgen
  commands:
    - pkg-config --variable=pythondir xcb-proto  # [not win]
    - set "PKG_CONFIG_PATH=%LIBRARY_PREFIX%\share\pkgconfig" && pkg-config --variable=pythondir xcb-proto  # [win]

about:
  home: http://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: "Provides the XML-XCB protocol descriptions that libxcb uses to generate the majority of its code and API"

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - pkgw
