{% set version = "1.17.0" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: xcb-proto
  version: {{ version }}

source:
  url: https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-{{ version }}.tar.gz
  sha256: 392d3c9690f8c8202a68fdb89c16fd55159ab8d65000a6da213f4a1576e97a16
  patches:
    - windows-pythondir.patch  # [win]

build:
  noarch: python
  number: 5
  detect_binary_files_with_prefix: true
  ignore_run_exports_from:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}

requirements:
  build:
    # uses m2w64 toolchain on windows, see conda_build_config.yaml
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - pkg-config
    - m2-autoconf                   # [win]
    - m2-automake{{ am_version }}   # [win]
    - m2-libtool                    # [win]
    - m2-base                       # [win]
    - m2-make                       # [win]
    - make                          # [unix]
    - autoconf                      # [unix]
    - automake                      # [unix]
    - gettext                       # [unix]
    - libtool                       # [unix]
  host:
    - python {{ python_min }}
    - xorg-util-macros
  run:
    - python >={{ python_min }}
    - __unix  # [unix]
    - __win   # [win]

test:
  requires:
    - python {{ python_min }}
    - pkg-config
  imports:
    - xcbgen
  commands:
    - pkg-config --variable=pythondir xcb-proto  # [not win]
    - set "PKG_CONFIG_PATH=%LIBRARY_PREFIX%\share\pkgconfig" && pkg-config --variable=pythondir xcb-proto  # [win]

about:
  home: http://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: "Provides the XML-XCB protocol descriptions that libxcb uses to generate the majority of its code and API"

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - pkgw
